//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minicore_Rivadeneira.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbf62c9ea3413d4d87b292aec9009e0e71Entities : DbContext
    {
        public dbf62c9ea3413d4d87b292aec9009e0e71Entities()
            : base("name=dbf62c9ea3413d4d87b292aec9009e0e71Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pas> Pases { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
