//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minicore_Rivadeneira.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pas
    {
        public int PaseID { get; set; }
        public int UsuarioID { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public string TtipoPase { get; set; }
        public Nullable<System.DateTime> FinTentativo { get; set; }
        public Nullable<int> pasesRestantes { get; set; }
        public Nullable<double> saldoRestante { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
